stages:
  load_data:
    cmd: python src/stage01_load_save.py --config=config/config.yaml
    deps: 
      - src/stage01_load_save.py
      - src/utils/all_utils.py
      - config/config.yaml
    outs:
      - artifacts/raw_local_dir/data.csv

  split_data:
    cmd: python src/stage02_split_data.py --config=config/config.yaml --params=params.yaml
    deps: 
      - src/stage02_split_data.py
      - src/utils/all_utils.py
      - config/config.yaml
      - artifacts/raw_local_dir/data.csv
    params:
      - base.random_state
      - base.test_size  
    outs:
      - artifacts/split_data_dir/train.csv
      - artifacts/split_data_dir/test.csv  

  class_balanced_data:
    cmd: python src/stage03_class_balanced_data.py --config=config/config.yaml 
    deps: 
      - src/stage03_class_balanced_data.py
      - src/utils/all_utils.py
      - config/config.yaml
      - artifacts/split_data_dir/train.csv
    
    outs:
      - artifacts/clean_data_dir/clean_data.csv
  train:
    cmd: python src/stage04_model_building.py --config=config/config.yaml 
    deps: 
      - src/stage04_model_building.py
      - src/utils/all_utils.py
      - config/config.yaml
      - artifacts/clean_data_dir/clean_data.csv

    
    outs:
      - artifacts/model_dir/logistic_regression.model     

  evaluate:
    cmd: python src/stage05_model_evaluation.py --config=config/config.yaml 
    
    deps:
      - src/stage05_model_evaluation.py
      - src/utils/all_utils.py
      - config/config.yaml
      - artifacts/split_data_dir/test.csv
      - artifacts/model_dir/logistic_regression.model
    outs:
      - artifacts/reports_dir/scores.txt     